name: Build APK with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build APK inside Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app kivy/buildozer:latest /bin/bash -c "
          buildozer init && \
          sed -i 's/^requirements =.*/requirements = kivy,cryptography/' buildozer.spec && \
          buildozer android debug
        "

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
