name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk unzip git libffi-dev libssl-dev sed
        pip install --upgrade pip
        pip install --user buildozer cython
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Android SDK + Accept Licenses
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdtools.zip
        unzip cmdtools.zip -d cmdline-tools
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
        yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;36.0.0"

    - name: Build APK
      env:
        ANDROIDSDK: $HOME/android-sdk
        ANDROIDNDK: $HOME/.buildozer/android/platform/android-ndk-r25b
        PATH: $HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/.local/bin:$PATH
      run: |
        buildozer init
        python3 -c "
with open('buildozer.spec', 'r') as f:
    lines = f.readlines()
with open('buildozer.spec', 'w') as f:
    for line in lines:
        if line.startswith('requirements ='):
            f.write('requirements = kivy,cryptography\n')
        else:
            f.write(line)
"
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
